# ===================================================================
# SPRING BOOT PROPERTIES
# ===================================================================
spring:
  datasource:
    url: jdbc:h2:mem:test
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# ===================================================================
# AWS PROPERTIES
# ===================================================================
cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-306614265263
    region:
      static: ap-northeast-2
    stack:
      auto: false

# ===================================================================
# JWT PROPERTIES
# ===================================================================
jwt:
  tokenSecretKey: ${JWT_TOKEN_SECRET_KEY}
  tokenIssuer: ${JWT_TOKEN_ISSUER}
  tokenType: ${JWT_TOKEN_TYPE}
