# ===================================================================
# SPRING BOOT PROPERTIES
# ===================================================================
spring:
  datasource:
    url: jdbc:h2:mem:test
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# ===================================================================
# AWS PROPERTIES
# ===================================================================
cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-306614265263
    region:
      static: ap-northeast-2
    stack:
      auto: false

---

spring:
  profiles:
    on-profile: prod
  datasource:
    url: aa1mnxep5graj8m.c0jea8ollihw.ap-northeast-2.rds.amazonaws.com:3306
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSOWRD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
